"""empty message

Revision ID: 062b9642356b
Revises: 46db44d055bb
Create Date: 2022-02-12 18:51:51.573053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062b9642356b'
down_revision = '46db44d055bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('base_xp', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('p_type', sa.String(), nullable=True),
    sa.Column('ability', sa.String(), nullable=True),
    sa.Column('move', sa.String(), nullable=True),
    sa.Column('sprite', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pokemon_trainer',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'trainer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_trainer')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
