"""empty message

Revision ID: 46db44d055bb
Revises: c16233be6e26
Create Date: 2022-02-10 21:14:55.438503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46db44d055bb'
down_revision = 'c16233be6e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('base_xp', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('p_type', sa.String(), nullable=True),
    sa.Column('ability', sa.String(), nullable=True),
    sa.Column('move', sa.String(), nullable=True),
    sa.Column('sprite', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_foreign_key(None, 'pokemon_trainer', 'pokemon', ['pokemon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon_trainer', type_='foreignkey')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
